name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Deploy to GitHub
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>gh</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          
          mvn versions:set -DnewVersion=1.0.${{ github.run_number }} -P github-build
          
          mvn clean install -P github-build
          
          mvn --batch-mode -DuseGitHubPackages=true deploy -P github-deploy,github-build
        env:
          GITHUB_ACTOR: vincentbuchholz
          GITHUB_TOKEN: ${{ secrets.PACKAGE_DEPLOY_TOKEN }}
